CREATE TABLE [dbo].[MedicationStatement] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [Status]                   NVARCHAR (MAX)   NULL,
    [PrescribingAgencyCode]    NVARCHAR (MAX)   NULL,
    [PrescribingAgencyDisplay] NVARCHAR (MAX)   NULL,
    [LastIssueDateUTC]         DATETIME         NULL,
    [DateAssertedUTC]          DATETIME         NULL,
    [DosageLastChanged]        DATETIME         NULL,
    [MedicationId]             UNIQUEIDENTIFIER NULL,
    [EffectivePeriodStart]     DATETIME         NULL,
    [EffectivePeriodEnd]       DATETIME         NULL,
    [Subject]                  UNIQUEIDENTIFIER NULL,
    [Taken]                    NVARCHAR (MAX)   NULL,
    [Identifier]               UNIQUEIDENTIFIER NULL,
    [Dosage]                   UNIQUEIDENTIFIER NULL,
    [BasedOn]                  UNIQUEIDENTIFIER NULL,
    [PartOf]                   UNIQUEIDENTIFIER NULL,
    [Context]                  UNIQUEIDENTIFIER NULL,
    [Category]                 NVARCHAR (MAX)   NULL,
    [InformationSource]        UNIQUEIDENTIFIER NULL,
    [ReasonReference]          UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__Medicatio__Medic__3D2915A8] FOREIGN KEY ([MedicationId]) REFERENCES [dbo].[Medication] ([Id]),
    CONSTRAINT [FK__Medicatio__Patie__3E1D39E1] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id])
);

