CREATE TABLE [dbo].[MedicationRequest] (
    [Id]                                  UNIQUEIDENTIFIER NOT NULL,
    [NumberOfRepeatPrescriptionsAllowed]  INT              NULL,
    [NumberOfRepeatPrescriptionsIssued]   INT              NULL,
    [PrescriptionType]                    UNIQUEIDENTIFIER NULL,
    [CrossCareIdentifier]                 UNIQUEIDENTIFIER NULL,
    [GroupIdentifier]                     UNIQUEIDENTIFIER NULL,
    [Status]                              UNIQUEIDENTIFIER NULL,
    [Intent]                              UNIQUEIDENTIFIER NULL,
    [MedicationId]                        UNIQUEIDENTIFIER NULL,
    [Subject]                             UNIQUEIDENTIFIER NULL,
    [AuthoredOnUTC]                       DATETIME         NULL,
    [RecorderGuid]                        UNIQUEIDENTIFIER NULL,
    [DosageInstructionPatientInstruction] NVARCHAR (MAX)   NULL,
    [MedicationDispenseRequestId]         UNIQUEIDENTIFIER NULL,
    [AuthorizationExpiry]                 DATETIME         NULL,
    [Identifier]                          UNIQUEIDENTIFIER NULL,
    [Definition]                          UNIQUEIDENTIFIER NULL,
    [BasedOn]                             UNIQUEIDENTIFIER NULL,
    [Category]                            UNIQUEIDENTIFIER NULL,
    [Priority]                            UNIQUEIDENTIFIER NULL,
    [Context]                             UNIQUEIDENTIFIER NULL,
    [SupportingInformation]               UNIQUEIDENTIFIER NULL,
    [RequesterAgent]                      UNIQUEIDENTIFIER NULL,
    [RequesterOnBehalfOf]                 UNIQUEIDENTIFIER NULL,
    [Recorder]                            UNIQUEIDENTIFIER NULL,
    [Reason]                              UNIQUEIDENTIFIER NULL,
    [NoteAuthor]                          UNIQUEIDENTIFIER NULL,
    [Note]                                NVARCHAR (MAX)   NULL,
    [Dosage]                              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Medicati__3214EC07905EAC71] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK__Medicatio__Medic__3864608B] FOREIGN KEY ([MedicationId]) REFERENCES [dbo].[Medication] ([Id]),
    CONSTRAINT [FK__Medicatio__Medic__395884C4] FOREIGN KEY ([MedicationDispenseRequestId]) REFERENCES [dbo].[MedicationDispenseRequest] ([Id]),
    CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK__Medicatio__Recor__3B40CD36] FOREIGN KEY ([RecorderGuid]) REFERENCES [dbo].[Practicioner] ([Id])
);

