CREATE TABLE [dbo].[Observation] (
    [Id]                        UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]                NVARCHAR (200)   NULL,
    [Status]                    NVARCHAR (MAX)   NULL,
    [Category]                  NVARCHAR (MAX)   NULL,
    [Code]                      NVARCHAR (MAX)   NULL,
    [SubjectId]                 UNIQUEIDENTIFIER NULL,
    [ContextId]                 UNIQUEIDENTIFIER NULL,
    [EffectiveDate]             DATETIME         NULL,
    [EffectiveDateFrom]         DATETIME         NULL,
    [EffectiveDateTo]           DATETIME         NULL,
    [Issued]                    DATETIME         NULL,
    [PerformerId]               UNIQUEIDENTIFIER NULL,
    [Interpretation]            NVARCHAR (MAX)   NULL,
    [DataAbsentReason]          NVARCHAR (MAX)   NULL,
    [Comment]                   NVARCHAR (MAX)   NULL,
    [BodySite]                  NVARCHAR (MAX)   NULL,
    [Method]                    NVARCHAR (MAX)   NULL,
    [Device]                    UNIQUEIDENTIFIER NULL,
    [ReferenceRangeLow]         int              NULL,
    [ReferenceRangeHigh]        int              NULL,
    [ReferenceRangeType]        NVARCHAR (MAX)   NULL,
    [ReferenceRangeAppliesTo]   NVARCHAR (MAX)   NULL,
    [ReferenceRangeAge]         NVARCHAR (MAX)   NULL,
    [RelatedTo]                 UNIQUEIDENTIFIER NULL,
    [Entityid]                  UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC),
    FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Practicioner] ([Id]),
    CONSTRAINT [FK__Observati__Conte__534D60F1] FOREIGN KEY ([ContextId]) REFERENCES [dbo].[Encounter] ([Id]),
    CONSTRAINT [FK__Observati__Subje__40F9A68C] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK__Observati__Perf] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Entity] ([Id]),
    CONSTRAINT [FK__Observati__Device] FOREIGN KEY ([Device]) REFERENCES [dbo].[Device] ([Id]),
    CONSTRAINT [FK__Observati__Observation] FOREIGN KEY ([RelatedTo]) REFERENCES [dbo].[Observation] ([Id]),
    CONSTRAINT [FK__Observati__Entity] FOREIGN KEY ([Entityid]) REFERENCES [dbo].[Entity] ([Id]),
);

