CREATE TABLE [dbo].[Patient] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]               NVARCHAR (255)   NOT NULL,
    [ManagingOrganization]     UNIQUEIDENTIFIER NOT NULL,
    [Practicioner]             UNIQUEIDENTIFIER NOT NULL,
    [HomeAddress]              UNIQUEIDENTIFIER NULL,
    [Sex]                      NVARCHAR (255)   NULL,
    [DateOfBirthUTC]           DATETIME         NOT NULL,
    [DateOfDeathUTC]           DATETIME         NULL,
    [Title]                    NVARCHAR (255)   NULL,
    [GivenName]                NVARCHAR (255)   NOT NULL,
    [MiddleNames]              NVARCHAR (MAX)   NULL,
    [Surname]                  NVARCHAR (255)   NOT NULL,
    [DateOfRegistrationUTC]    DATETIME         NULL,
    [NhsNumber]                NVARCHAR (255)   NULL,
    [PatientNumber]            NVARCHAR (255)   NULL,
    [PatientTypeDescription]   NVARCHAR (255)   NULL,
    [DummyType]                NVARCHAR (255)   NULL,
    [ResidentialInstituteCode] NVARCHAR (255)   NULL,
    [NHSNumberStatus]          NVARCHAR (255)   NULL,
    [CarerName]                NVARCHAR (255)   NULL,
    [CarerRelation]            NVARCHAR (255)   NULL,
    [PersonGuid]               NVARCHAR (255)   NULL,
    [DateOfDeactivation]       DATETIME         NULL,
    [Deleted]                  BIT              NULL,
    [Active]                   BIT              NULL,
    [SpineSensitive]           BIT              NULL,
    [IsConfidential]           BIT              NULL,
    [EmailAddress]             NVARCHAR (255)   NULL,
    [HomePhone]                NVARCHAR (20)    NULL,
    [MobilePhone]              NVARCHAR (20)    NULL,
    [ProcessingId]             NVARCHAR (255)   NULL,
    [Ethnicity]                NVARCHAR (255)   NULL,
    [Religion]                 NVARCHAR (255)   NULL,
    [NominatedPharmacy]        UNIQUEIDENTIFIER NULL,
    [EntityId]                 UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Patient__DBA60F19AE6332BC] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Patient_Organization] FOREIGN KEY ([ManagingOrganization]) REFERENCES [dbo].[Organization] ([Id]),
    CONSTRAINT [FK_Patient_Organization1] FOREIGN KEY ([NominatedPharmacy]) REFERENCES [dbo].[Organization] ([Id]),
    CONSTRAINT [FK_Patient_Patient] FOREIGN KEY ([Id]) REFERENCES [dbo].[Patient] ([Id]),
    CONSTRAINT [FK_Patient_Practicioner] FOREIGN KEY ([Practicioner]) REFERENCES [dbo].[Practicioner] ([Id])
);

