/*
Deployment script for GPData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar RunAutomatedScripts "false"
:setvar DatabaseName "GPData"
:setvar DefaultFilePrefix "GPData"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
    DECLARE @rc      int,                       -- return code
            @fn      nvarchar(4000),            -- file name for back up
            @dir     nvarchar(4000)             -- backup directory

    EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @dir output, 'no_output'
    if (@rc = 0) SELECT @dir = @dir + N'\'

    IF (@dir IS NULL)
    BEGIN 
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'DefaultData', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\'
    END

    IF (@dir IS NULL)
    BEGIN
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\Setup', N'SQLDataRoot', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\Backup\'
    END

    IF (@dir IS NULL)
    BEGIN
        SELECT @dir = N'$(DefaultDataPath)'
    END

    SELECT  @fn = @dir + N'$(DatabaseName)' + N'-' + 
            CONVERT(nchar(8), GETDATE(), 112) + N'-' + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(hh, GETDATE()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(mi, getdate()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(ss, getdate()))), 2) + 
            N'.bak' 
            BACKUP DATABASE [$(DatabaseName)] TO DISK = @fn
END
GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Contacts_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Contacts] DROP CONSTRAINT [FK_Patient_Contacts_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__AllergyIn__NoteA__31B762FC]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK__AllergyIn__NoteA__31B762FC];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Subje__2CF2ADDF]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance] DROP CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Address_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Address] DROP CONSTRAINT [FK_Patient_Address_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Patient]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient1]...';


GO
ALTER TABLE [dbo].[Patient_Links] DROP CONSTRAINT [FK_Patient_Links_Patient1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Practicioner]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Practicioner];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Condition] DROP CONSTRAINT [FK__Condition__Subje__40F9A68C];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Patient]...';


GO
ALTER TABLE [dbo].[ReferralRequest] DROP CONSTRAINT [FK_ReferralRequest_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Encounter__Patie__412EB0B6]...';


GO
ALTER TABLE [dbo].[Encounter] DROP CONSTRAINT [FK__Encounter__Patie__412EB0B6];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Specimen__Subjec__6FB49575]...';


GO
ALTER TABLE [dbo].[Specimen] DROP CONSTRAINT [FK__Specimen__Subjec__6FB49575];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Organization]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Organization];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Subje__1EA48E88]...';


GO
ALTER TABLE [dbo].[DiagnosticReport] DROP CONSTRAINT [FK__Diagnosti__Subje__1EA48E88];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Immunizat__Subje__6FE99F9F]...';


GO
ALTER TABLE [dbo].[Immunization] DROP CONSTRAINT [FK__Immunizat__Subje__6FE99F9F];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3E1D39E1]...';


GO
ALTER TABLE [dbo].[MedicationStatement] DROP CONSTRAINT [FK__Medicatio__Patie__3E1D39E1];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Observati__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Observation] DROP CONSTRAINT [FK__Observati__Subje__40F9A68C];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_Subject]...';


GO
ALTER TABLE [dbo].[ProcedureRequest] DROP CONSTRAINT [FK_ProcedureRequest_Subject];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3A4CA8FD]...';


GO
ALTER TABLE [dbo].[MedicationRequest] DROP CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Links] DROP CONSTRAINT [FK_Patient_Links_Patient];


GO
PRINT N'Dropping SqlForeignKeyConstraint [dbo].[FK_Patient_Organization1]...';


GO
ALTER TABLE [dbo].[Patient] DROP CONSTRAINT [FK_Patient_Organization1];


GO
PRINT N'Starting rebuilding table [dbo].[Patient]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Patient] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]               NVARCHAR (255)   NOT NULL,
    [ManagingOrganization]     UNIQUEIDENTIFIER NOT NULL,
    [Practicioner]             UNIQUEIDENTIFIER NOT NULL,
    [HomeAddress]              UNIQUEIDENTIFIER NULL,
    [Sex]                      NVARCHAR (255)   NULL,
    [DateOfBirthUTC]           DATETIME         NOT NULL,
    [DateOfDeathUTC]           DATETIME         NULL,
    [Title]                    NVARCHAR (255)   NULL,
    [GivenName]                NVARCHAR (255)   NOT NULL,
    [MiddleNames]              NVARCHAR (MAX)   NULL,
    [Surname]                  NVARCHAR (255)   NOT NULL,
    [DateOfRegistrationUTC]    DATETIME         NULL,
    [NhsNumber]                NVARCHAR (255)   NULL,
    [PatientNumber]            NVARCHAR (255)   NULL,
    [PatientTypeDescription]   NVARCHAR (255)   NULL,
    [DummyType]                NVARCHAR (255)   NULL,
    [ResidentialInstituteCode] NVARCHAR (255)   NULL,
    [NHSNumberStatus]          NVARCHAR (255)   NULL,
    [CarerName]                NVARCHAR (255)   NULL,
    [CarerRelation]            NVARCHAR (255)   NULL,
    [PersonGuid]               NVARCHAR (255)   NULL,
    [DateOfDeactivation]       DATETIME         NULL,
    [Deleted]                  BIT              NULL,
    [Active]                   BIT              NULL,
    [SpineSensitive]           BIT              NULL,
    [IsConfidential]           BIT              NULL,
    [EmailAddress]             NVARCHAR (255)   NULL,
    [HomePhone]                NVARCHAR (20)    NULL,
    [MobilePhone]              NVARCHAR (20)    NULL,
    [ProcessingId]             NVARCHAR (255)   NULL,
    [Ethnicity]                NVARCHAR (255)   NULL,
    [Religion]                 NVARCHAR (255)   NULL,
    [NominatedPharmacy]        UNIQUEIDENTIFIER NULL,
    [EntityId]                 UNIQUEIDENTIFIER NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK__Patient__DBA60F19AE6332BC1] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Patient])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_Patient] ([Id], [OriginalId], [ManagingOrganization], [Practicioner], [Sex], [DateOfBirthUTC], [DateOfDeathUTC], [Title], [GivenName], [MiddleNames], [Surname], [DateOfRegistrationUTC], [NhsNumber], [PatientNumber], [PatientTypeDescription], [DummyType], [ResidentialInstituteCode], [NHSNumberStatus], [CarerName], [CarerRelation], [PersonGuid], [DateOfDeactivation], [Deleted], [Active], [SpineSensitive], [IsConfidential], [EmailAddress], [HomePhone], [MobilePhone], [ProcessingId], [Ethnicity], [Religion], [NominatedPharmacy])
        SELECT   [Id],
                 [OriginalId],
                 [ManagingOrganization],
                 [Practicioner],
                 [Sex],
                 [DateOfBirthUTC],
                 [DateOfDeathUTC],
                 [Title],
                 [GivenName],
                 [MiddleNames],
                 [Surname],
                 [DateOfRegistrationUTC],
                 [NhsNumber],
                 [PatientNumber],
                 [PatientTypeDescription],
                 [DummyType],
                 [ResidentialInstituteCode],
                 [NHSNumberStatus],
                 [CarerName],
                 [CarerRelation],
                 [PersonGuid],
                 [DateOfDeactivation],
                 [Deleted],
                 [Active],
                 [SpineSensitive],
                 [IsConfidential],
                 [EmailAddress],
                 [HomePhone],
                 [MobilePhone],
                 [ProcessingId],
                 [Ethnicity],
                 [Religion],
                 [NominatedPharmacy]
        FROM     [dbo].[Patient]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[Patient];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Patient]', N'Patient';

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_constraint_PK__Patient__DBA60F19AE6332BC1]', N'PK__Patient__DBA60F19AE6332BC', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Contacts_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Contacts] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Contacts_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__AllergyIn__NoteA__31B762FC]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK__AllergyIn__NoteA__31B762FC] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__AllergyIn__Subje__2CF2ADDF]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[AllergyIntollerance] WITH NOCHECK
    ADD CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Address_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Address] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Address_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Patient] FOREIGN KEY ([Id]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Links] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Links_Patient1] FOREIGN KEY ([LinkedPatient]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Practicioner]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Practicioner] FOREIGN KEY ([Practicioner]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Condition] WITH NOCHECK
    ADD CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ReferralRequest_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ReferralRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ReferralRequest_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Encounter__Patie__412EB0B6]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Encounter] WITH NOCHECK
    ADD CONSTRAINT [FK__Encounter__Patie__412EB0B6] FOREIGN KEY ([PatientGuid]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Specimen__Subjec__6FB49575]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Specimen] WITH NOCHECK
    ADD CONSTRAINT [FK__Specimen__Subjec__6FB49575] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Organization]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Organization] FOREIGN KEY ([ManagingOrganization]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Diagnosti__Subje__1EA48E88]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[DiagnosticReport] WITH NOCHECK
    ADD CONSTRAINT [FK__Diagnosti__Subje__1EA48E88] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Immunizat__Subje__6FE99F9F]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Immunization] WITH NOCHECK
    ADD CONSTRAINT [FK__Immunizat__Subje__6FE99F9F] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3E1D39E1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[MedicationStatement] WITH NOCHECK
    ADD CONSTRAINT [FK__Medicatio__Patie__3E1D39E1] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Observati__Subje__40F9A68C]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Observation] WITH NOCHECK
    ADD CONSTRAINT [FK__Observati__Subje__40F9A68C] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_ProcedureRequest_Subject]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[ProcedureRequest] WITH NOCHECK
    ADD CONSTRAINT [FK_ProcedureRequest_Subject] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK__Medicatio__Patie__3A4CA8FD]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[MedicationRequest] WITH NOCHECK
    ADD CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Links_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient_Links] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Links_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Patient_Organization1]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Patient] WITH NOCHECK
    ADD CONSTRAINT [FK_Patient_Organization1] FOREIGN KEY ([NominatedPharmacy]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating SqlForeignKeyConstraint [dbo].[FK_Compositio_Patient]...';


GO
WAITFOR DELAY '00:00.010';

ALTER TABLE [dbo].[Composition] WITH NOCHECK
    ADD CONSTRAINT [FK_Compositio_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

IF NOT EXISTS (SELECT * FROM [dbo].[EntityType])
BEGIN
	-- Disable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT all'

	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (1,N'Organization')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (2,N'Location')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (3,N'Patient')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (4,N'Practitioner')
	
	-- Re-enable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all';	

END
GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Patient_Contacts] WITH CHECK CHECK CONSTRAINT [FK_Patient_Contacts_Patient];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK__AllergyIn__NoteA__31B762FC];

ALTER TABLE [dbo].[AllergyIntollerance] WITH CHECK CHECK CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF];

ALTER TABLE [dbo].[Patient_Address] WITH CHECK CHECK CONSTRAINT [FK_Patient_Address_Patient];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Patient];

ALTER TABLE [dbo].[Patient_Links] WITH CHECK CHECK CONSTRAINT [FK_Patient_Links_Patient1];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Practicioner];

ALTER TABLE [dbo].[Condition] WITH CHECK CHECK CONSTRAINT [FK__Condition__Subje__40F9A68C];

ALTER TABLE [dbo].[ReferralRequest] WITH CHECK CHECK CONSTRAINT [FK_ReferralRequest_Patient];

ALTER TABLE [dbo].[Encounter] WITH CHECK CHECK CONSTRAINT [FK__Encounter__Patie__412EB0B6];

ALTER TABLE [dbo].[Specimen] WITH CHECK CHECK CONSTRAINT [FK__Specimen__Subjec__6FB49575];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Organization];

ALTER TABLE [dbo].[DiagnosticReport] WITH CHECK CHECK CONSTRAINT [FK__Diagnosti__Subje__1EA48E88];

ALTER TABLE [dbo].[Immunization] WITH CHECK CHECK CONSTRAINT [FK__Immunizat__Subje__6FE99F9F];

ALTER TABLE [dbo].[MedicationStatement] WITH CHECK CHECK CONSTRAINT [FK__Medicatio__Patie__3E1D39E1];

ALTER TABLE [dbo].[Observation] WITH CHECK CHECK CONSTRAINT [FK__Observati__Subje__40F9A68C];

ALTER TABLE [dbo].[ProcedureRequest] WITH CHECK CHECK CONSTRAINT [FK_ProcedureRequest_Subject];

ALTER TABLE [dbo].[MedicationRequest] WITH CHECK CHECK CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD];

ALTER TABLE [dbo].[Patient_Links] WITH CHECK CHECK CONSTRAINT [FK_Patient_Links_Patient];

ALTER TABLE [dbo].[Patient] WITH CHECK CHECK CONSTRAINT [FK_Patient_Organization1];

ALTER TABLE [dbo].[Composition] WITH CHECK CHECK CONSTRAINT [FK_Compositio_Patient];


GO
PRINT N'Update complete.';


GO
