/*
Deployment script for GPData

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar RunAutomatedScripts "false"
:setvar DatabaseName "GPData"
:setvar DefaultFilePrefix "GPData"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL)
BEGIN
    DECLARE @rc      int,                       -- return code
            @fn      nvarchar(4000),            -- file name for back up
            @dir     nvarchar(4000)             -- backup directory

    EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'BackupDirectory', @dir output, 'no_output'
    if (@rc = 0) SELECT @dir = @dir + N'\'

    IF (@dir IS NULL)
    BEGIN 
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\MSSQLServer', N'DefaultData', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\'
    END

    IF (@dir IS NULL)
    BEGIN
        EXEC @rc = [master].[dbo].[xp_instance_regread] N'HKEY_LOCAL_MACHINE', N'Software\Microsoft\MSSQLServer\Setup', N'SQLDataRoot', @dir output, 'no_output'
        if (@rc = 0) SELECT @dir = @dir + N'\Backup\'
    END

    IF (@dir IS NULL)
    BEGIN
        SELECT @dir = N'$(DefaultDataPath)'
    END

    SELECT  @fn = @dir + N'$(DatabaseName)' + N'-' + 
            CONVERT(nchar(8), GETDATE(), 112) + N'-' + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(hh, GETDATE()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(mi, getdate()))), 2) + 
            RIGHT(N'0' + RTRIM(CONVERT(nchar(2), DATEPART(ss, getdate()))), 2) + 
            N'.bak' 
            BACKUP DATABASE [$(DatabaseName)] TO DISK = @fn
END
GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating database $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = AUTO, OPERATION_MODE = READ_WRITE, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET TEMPORAL_HISTORY_RETENTION ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Dropping Permission Permission...';


GO
REVOKE VIEW ANY COLUMN ENCRYPTION KEY DEFINITION TO PUBLIC CASCADE;


GO
PRINT N'Dropping Permission Permission...';


GO
REVOKE VIEW ANY COLUMN MASTER KEY DEFINITION TO PUBLIC CASCADE;


GO
PRINT N'Creating Table [dbo].[ActivityDefinition]...';


GO
CREATE TABLE [dbo].[ActivityDefinition] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [IdentifierId]          UNIQUEIDENTIFIER NULL,
    [Version]               NVARCHAR (50)    NULL,
    [Name]                  NVARCHAR (50)    NULL,
    [Title]                 NVARCHAR (50)    NULL,
    [Status]                NVARCHAR (50)    NULL,
    [Experimental]          BIT              NULL,
    [Date]                  DATETIME         NULL,
    [Publisher]             NVARCHAR (50)    NULL,
    [Description]           NVARCHAR (MAX)   NULL,
    [Purpose]               NVARCHAR (MAX)   NULL,
    [Usage]                 NVARCHAR (MAX)   NULL,
    [ApprovalDate]          DATETIME         NULL,
    [LastReviewDate]        DATETIME         NULL,
    [EffectiveStart]        DATETIME         NULL,
    [EffectiveEnd]          DATETIME         NULL,
    [UsageContextCode]      NVARCHAR (50)    NULL,
    [UsageContextQuantity]  DECIMAL (18, 2)  NULL,
    [UsageContextRangeLow]  INT              NULL,
    [UsageContextRangeHigh] INT              NULL,
    [Jurisdiction]          NVARCHAR (50)    NULL,
    [Topic]                 NVARCHAR (50)    NULL,
    [Contributor]           NVARCHAR (50)    NULL,
    [Contact]               NVARCHAR (50)    NULL,
    [Copyright]             NVARCHAR (50)    NULL,
    [RelatedArtifactId]     UNIQUEIDENTIFIER NULL,
    [Library]               NVARCHAR (50)    NULL,
    [Code]                  NVARCHAR (50)    NULL,
    [TimingDate]            DATETIME         NULL,
    [TimingPeriodStart]     DATETIME         NULL,
    [TimingPeriodEnd]       DATETIME         NULL,
    [TimingRangeLow]        INT              NULL,
    [TimingRangeHigh]       INT              NULL,
    [LocationId]            UNIQUEIDENTIFIER NULL,
    [ParticipantType]       NVARCHAR (50)    NULL,
    [ParticipantRoleId]     NVARCHAR (50)    NULL,
    [ProductId]             UNIQUEIDENTIFIER NULL,
    [Quantity]              INT              NULL,
    [DosageId]              UNIQUEIDENTIFIER NULL,
    [BodySite]              NVARCHAR (50)    NULL,
    [TransformId]           UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Address]...';


GO
CREATE TABLE [dbo].[Address] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Use]                 NVARCHAR (255)   NULL,
    [HouseNameFlatNumber] NVARCHAR (255)   NULL,
    [NumberAndStreet]     NVARCHAR (255)   NULL,
    [Village]             NVARCHAR (255)   NULL,
    [Town]                NVARCHAR (255)   NULL,
    [County]              NVARCHAR (255)   NULL,
    [Postcode]            NVARCHAR (20)    NULL,
    [From]                DATETIME         NULL,
    [To]                  DATETIME         NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[AllergyIntollerance]...';


GO
CREATE TABLE [dbo].[AllergyIntollerance] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [Identifier]            UNIQUEIDENTIFIER NULL,
    [ReasonEnded]           NVARCHAR (MAX)   NULL,
    [OnsetDate]             DATETIME         NULL,
    [OnsetAge]              DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]      DATETIME         NULL,
    [OnsetPeriodEnd]        DATETIME         NULL,
    [AllergyEndDate]        DATETIME         NULL,
    [ClinicalStatus]        NVARCHAR (MAX)   NULL,
    [VerificationStatus]    NVARCHAR (MAX)   NULL,
    [Criticality]           NVARCHAR (MAX)   NULL,
    [Code]                  NVARCHAR (MAX)   NULL,
    [Type]                  NVARCHAR (MAX)   NULL,
    [Category]              NVARCHAR (MAX)   NULL,
    [Subject]               UNIQUEIDENTIFIER NULL,
    [AssertedDate]          DATETIME         NULL,
    [Asserter]              UNIQUEIDENTIFIER NULL,
    [Recorder]              UNIQUEIDENTIFIER NULL,
    [LastOccurance]         DATETIME         NULL,
    [NoteAuthored]          DATETIME         NULL,
    [NoteAuthor]            UNIQUEIDENTIFIER NULL,
    [ReactionSubstance]     NVARCHAR (MAX)   NULL,
    [ReactionManifestation] NVARCHAR (MAX)   NULL,
    [ReactionDescription]   NVARCHAR (MAX)   NULL,
    [ReactionExposureRate]  NVARCHAR (MAX)   NULL,
    [Encounter]             UNIQUEIDENTIFIER NOT NULL,
    [Evidence]              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__AllergyI__A2B5777CD5983ADB] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Appointment]...';


GO
CREATE TABLE [dbo].[Appointment] (
    [Id]                            UNIQUEIDENTIFIER NOT NULL,
    [AppointmentCancellationReason] NVARCHAR (255)   NULL,
    [BookingOrganizationId]         UNIQUEIDENTIFIER NOT NULL,
    [PracticionerRole]              NVARCHAR (255)   NULL,
    [DeliveryChannel]               NVARCHAR (255)   NULL,
    [IdentifierId]                  UNIQUEIDENTIFIER NOT NULL,
    [Status]                        NVARCHAR (255)   NOT NULL,
    [ServiceCategory]               NVARCHAR (255)   NULL,
    [ServiceType]                   NVARCHAR (255)   NULL,
    [Speciality]                    NVARCHAR (255)   NULL,
    [Reason]                        NVARCHAR (255)   NULL,
    [Priority]                      INT              NULL,
    [Description]                   NVARCHAR (255)   NULL,
    [Start]                         DATETIME2 (7)    NOT NULL,
    [End]                           DATETIME2 (7)    NOT NULL,
    [MinutesDuration]               INT              NULL,
    [Created]                       DATETIME2 (7)    NULL,
    [Comment]                       NVARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Appointment_Participant]...';


GO
CREATE TABLE [dbo].[Appointment_Participant] (
    [AppointmentId] UNIQUEIDENTIFIER NOT NULL,
    [ParticipantId] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Appointment_Slots]...';


GO
CREATE TABLE [dbo].[Appointment_Slots] (
    [AppointmentId] UNIQUEIDENTIFIER NOT NULL,
    [SlotId]        UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Coding]...';


GO
CREATE TABLE [dbo].[Coding] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [ReadCode]     VARCHAR (250)    NULL,
    [SnomedCode]   VARCHAR (250)    NULL,
    [LocalCode]    VARCHAR (250)    NULL,
    [NationalCode] VARCHAR (250)    NULL,
    [Description]  VARCHAR (250)    NULL,
    CONSTRAINT [PK_Coding] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Composition]...';


GO
CREATE TABLE [dbo].[Composition] (
    [Id]                         UNIQUEIDENTIFIER NOT NULL,
    [Identifier]                 UNIQUEIDENTIFIER NULL,
    [CrossCareSettingIdentifier] UNIQUEIDENTIFIER NULL,
    [Status]                     NVARCHAR (MAX)   NULL,
    [Type]                       NVARCHAR (MAX)   NULL,
    [Class]                      NVARCHAR (MAX)   NULL,
    [Subject]                    UNIQUEIDENTIFIER NULL,
    [Encounter]                  UNIQUEIDENTIFIER NULL,
    [Author]                     UNIQUEIDENTIFIER NULL,
    [Observation]                NVARCHAR (MAX)   NULL,
    [Problem]                    NVARCHAR (MAX)   NULL,
    [Title]                      NVARCHAR (MAX)   NULL,
    [Code]                       NVARCHAR (MAX)   NULL,
    [OrderedByCode]              NVARCHAR (MAX)   NULL,
    [CareSettingType]            NVARCHAR (MAX)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Condition]...';


GO
CREATE TABLE [dbo].[Condition] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [Identifier]           UNIQUEIDENTIFIER NULL,
    [ActualProblem]        UNIQUEIDENTIFIER NULL,
    [ProblemSignificance]  NVARCHAR (MAX)   NULL,
    [Episode]              NVARCHAR (MAX)   NULL,
    [ClinicalStatus]       NVARCHAR (MAX)   NULL,
    [VerificationStatus]   NVARCHAR (MAX)   NULL,
    [Severity]             NVARCHAR (MAX)   NULL,
    [Code]                 NVARCHAR (MAX)   NULL,
    [BodySite]             NVARCHAR (MAX)   NULL,
    [Subject]              UNIQUEIDENTIFIER NULL,
    [Context]              UNIQUEIDENTIFIER NULL,
    [OnsetDate]            DATETIME         NULL,
    [OnsetAge]             DECIMAL (18, 2)  NULL,
    [OnsetPeriodStart]     DATETIME         NULL,
    [OnsetPeriodEnd]       DATETIME         NULL,
    [AbatementDate]        DATETIME         NULL,
    [AbatementAge]         DECIMAL (18, 2)  NULL,
    [AbatementPeriodStart] DATETIME         NULL,
    [AbatementPeriodEnd]   DATETIME         NULL,
    [Abatement]            BIT              NULL,
    [AssertedDate]         DATETIME         NOT NULL,
    [Asserter]             UNIQUEIDENTIFIER NOT NULL,
    [EvidenceCodes]        NVARCHAR (MAX)   NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteAuthored]         DATETIME         NULL,
    [NoteAuthor]           UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Conditio__A2B5777CD924092C] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Condition_Evidence]...';


GO
CREATE TABLE [dbo].[Condition_Evidence] (
    [ConditionId] UNIQUEIDENTIFIER NOT NULL,
    [EntityId]    UNIQUEIDENTIFIER NOT NULL,
    [Code]        NCHAR (100)      NULL
);


GO
PRINT N'Creating Table [dbo].[Condition_RelatedClinicalConditions]...';


GO
CREATE TABLE [dbo].[Condition_RelatedClinicalConditions] (
    [ConditionId] UNIQUEIDENTIFIER NOT NULL,
    [EntityId]    UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Condition_RelatedProblems]...';


GO
CREATE TABLE [dbo].[Condition_RelatedProblems] (
    [ConditionId] UNIQUEIDENTIFIER NOT NULL,
    [EntityId]    UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Contact]...';


GO
CREATE TABLE [dbo].[Contact] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [Title]          NVARCHAR (50)    NULL,
    [GivenName]      NVARCHAR (100)   NOT NULL,
    [MiddleName]     NVARCHAR (100)   NULL,
    [Surname]        NVARCHAR (100)   NOT NULL,
    [AddressID]      UNIQUEIDENTIFIER NULL,
    [OrganizationId] UNIQUEIDENTIFIER NULL,
    [Gender]         NVARCHAR (100)   NULL,
    [Relationship]   NVARCHAR (100)   NULL,
    [HomePhone]      NVARCHAR (100)   NULL,
    [MobilePhone]    NVARCHAR (100)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Device]...';


GO
CREATE TABLE [dbo].[Device] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [Identifier]   UNIQUEIDENTIFIER NOT NULL,
    [TypeCode]     NVARCHAR (255)   NULL,
    [TypeDisplay]  NVARCHAR (255)   NULL,
    [TypeSystem]   NVARCHAR (255)   NULL,
    [TypeVersion]  NVARCHAR (255)   NULL,
    [UserSelected] BIT              NULL,
    [Manufacturer] NVARCHAR (255)   NULL,
    [Model]        NVARCHAR (255)   NULL,
    [Version]      NVARCHAR (255)   NULL,
    [Owner]        UNIQUEIDENTIFIER NULL,
    [Locations]    NVARCHAR (255)   NULL,
    [Name]         NVARCHAR (255)   NULL,
    [Telecom]      NVARCHAR (255)   NULL,
    [Address]      UNIQUEIDENTIFIER NULL,
    [PartOf]       UNIQUEIDENTIFIER NULL,
    [Contact]      UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[DiagnosticReport]...';


GO
CREATE TABLE [dbo].[DiagnosticReport] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [Identifier]       UNIQUEIDENTIFIER NULL,
    [Status]           NVARCHAR (50)    NULL,
    [Assigner]         UNIQUEIDENTIFIER NOT NULL,
    [ProcedureRequest] UNIQUEIDENTIFIER NOT NULL,
    [Category]         NVARCHAR (50)    NULL,
    [Code]             NVARCHAR (50)    NULL,
    [Subject]          UNIQUEIDENTIFIER NOT NULL,
    [Encounter]        UNIQUEIDENTIFIER NULL,
    [EffectiveFrom]    DATETIME         NULL,
    [EffectiveTo]      DATETIME         NULL,
    [Issued]           DATETIME         NOT NULL,
    [Performer]        UNIQUEIDENTIFIER NULL,
    [Specimen]         UNIQUEIDENTIFIER NOT NULL,
    [Result]           UNIQUEIDENTIFIER NULL,
    [Conclusion]       NVARCHAR (50)    NULL,
    [CodedDiagnosis]   NVARCHAR (50)    NULL,
    [PresentedFrom]    NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Dosage]...';


GO
CREATE TABLE [dbo].[Dosage] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [Sequence]                 INT              NULL,
    [Text]                     NVARCHAR (MAX)   NULL,
    [Timing]                   UNIQUEIDENTIFIER NULL,
    [AdditionalInstruction]    NVARCHAR (MAX)   NULL,
    [PatientInstruction]       NVARCHAR (MAX)   NULL,
    [AsNeeded]                 BIT              NULL,
    [AsNeededCode]             NVARCHAR (MAX)   NULL,
    [Site]                     NVARCHAR (MAX)   NULL,
    [Route]                    NVARCHAR (MAX)   NULL,
    [Method]                   NVARCHAR (MAX)   NULL,
    [DoseRangeHigh]            INT              NULL,
    [DoseRangeLow]             INT              NULL,
    [Quantity]                 INT              NULL,
    [MaxDosePerPeriod]         DECIMAL (18, 4)  NULL,
    [MaxDosePerAdministration] INT              NULL,
    [MaxDosePerLifetime]       INT              NULL,
    [RateRatioNumerator]       DECIMAL (18, 4)  NULL,
    [RateRatioDenominator]     DECIMAL (18, 4)  NULL,
    [RateRangeLow]             INT              NULL,
    [RateRangeHigh]            INT              NULL,
    [RateQuantity]             INT              NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Encounter]...';


GO
CREATE TABLE [dbo].[Encounter] (
    [Id]            UNIQUEIDENTIFIER NOT NULL,
    [Identifier]    NVARCHAR (MAX)   NULL,
    [Status]        NVARCHAR (MAX)   NULL,
    [Type]          NVARCHAR (MAX)   NULL,
    [PatientGuid]   UNIQUEIDENTIFIER NULL,
    [PerformerId]   UNIQUEIDENTIFIER NULL,
    [RecorderId]    UNIQUEIDENTIFIER NULL,
    [PeriodStart]   DATETIME         NULL,
    [PeriodEnd]     DATETIME         NULL,
    [DurationValue] DECIMAL (18, 2)  NULL,
    [DurationUnit]  NVARCHAR (MAX)   NULL,
    [DurationCode]  NVARCHAR (MAX)   NULL,
    [EntityId]      UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Encounte__3214EC075BF916E0] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Entity]...';


GO
CREATE TABLE [dbo].[Entity] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [OriginalId] NVARCHAR (250)   NULL,
    [EntityType] INT              NOT NULL,
    CONSTRAINT [PK_Entity] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[EntityType]...';


GO
CREATE TABLE [dbo].[EntityType] (
    [EntityType] INT           NOT NULL,
    [EntityName] NVARCHAR (50) NOT NULL,
    CONSTRAINT [PK_EntityType] PRIMARY KEY CLUSTERED ([EntityType] ASC)
);


GO
PRINT N'Creating Table [dbo].[Equipment]...';


GO
CREATE TABLE [dbo].[Equipment] (
    [Id]           UNIQUEIDENTIFIER NOT NULL,
    [IdentifierID] NVARCHAR (100)   NULL,
    [TypeID]       NVARCHAR (100)   NULL,
    [Manufacturer] NVARCHAR (100)   NOT NULL,
    [Model]        NVARCHAR (100)   NOT NULL,
    [Version]      NVARCHAR (50)    NOT NULL,
    [OwnerID]      UNIQUEIDENTIFIER NULL,
    [Locations]    NVARCHAR (MAX)   NULL,
    [Name]         NVARCHAR (255)   NOT NULL,
    [Telecom]      NVARCHAR (20)    NULL,
    [AddressID]    UNIQUEIDENTIFIER NULL,
    [PartOfID]     UNIQUEIDENTIFIER NULL,
    [ContactID]    UNIQUEIDENTIFIER NULL,
    [EntityId]     UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Equipmen__3214EC07B1A029E1] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Identifier]...';


GO
CREATE TABLE [dbo].[Identifier] (
    [Use]         NVARCHAR (250)   NULL,
    [Type]        NVARCHAR (250)   NULL,
    [System]      NVARCHAR (MAX)   NULL,
    [Value]       NVARCHAR (MAX)   NULL,
    [PeriodStart] DATETIME         NULL,
    [PeriodEnd]   DATETIME         NULL,
    [Assigner]    NVARCHAR (250)   NULL,
    [Id]          UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Identifier] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Immunization]...';


GO
CREATE TABLE [dbo].[Immunization] (
    [Id]                   NVARCHAR (255)   NOT NULL,
    [Status]               NVARCHAR (255)   NULL,
    [Type]                 NVARCHAR (255)   NULL,
    [Class]                NVARCHAR (255)   NULL,
    [SubjectId]            UNIQUEIDENTIFIER NULL,
    [EncounterId]          UNIQUEIDENTIFIER NULL,
    [ActorId]              UNIQUEIDENTIFIER NULL,
    [LocationId]           UNIQUEIDENTIFIER NOT NULL,
    [ParentPresent]        BIT              NULL,
    [RecordedDate]         DATETIME         NULL,
    [Date]                 DATETIME         NULL,
    [PrimarySource]        BIT              NULL,
    [LotNumber]            NVARCHAR (255)   NULL,
    [Site]                 NVARCHAR (255)   NULL,
    [Route]                NVARCHAR (255)   NULL,
    [RouteText]            NVARCHAR (255)   NULL,
    [NoteAuthorId]         UNIQUEIDENTIFIER NULL,
    [NoteText]             NVARCHAR (MAX)   NULL,
    [NoteDate]             DATETIME         NULL,
    [ExpirationDate]       DATETIME         NULL,
    [VaccinationProcedure] NVARCHAR (255)   NULL,
    [VaccinationCode]      NVARCHAR (255)   NULL,
    [DoseQuantity]         DECIMAL (18, 2)  NULL,
    [ReactionReported]     BIT              NULL,
    [ReactionDetailId]     UNIQUEIDENTIFIER NULL,
    [ReactionDate]         DATETIME         NULL,
    [DoseSequence]         INT              NULL,
    [Description]          NVARCHAR (MAX)   NULL,
    [AuthorityId]          UNIQUEIDENTIFIER NULL,
    [Series]               NVARCHAR (255)   NULL,
    [SeriesDoses]          INT              NULL,
    [TargetDisease]        NVARCHAR (255)   NULL,
    [DoseStatus]           NVARCHAR (255)   NULL,
    [DoseStatusReason]     NVARCHAR (255)   NULL,
    [EntityId]             UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Immuniza__A2B5777C37B1E40D] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Location]...';


GO
CREATE TABLE [dbo].[Location] (
    [Id]                     UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]             NVARCHAR (255)   NOT NULL,
    [ODSSiteCodeID]          NVARCHAR (50)    NULL,
    [Status]                 NVARCHAR (50)    NULL,
    [OperationalStatus]      NVARCHAR (50)    NULL,
    [Name]                   NVARCHAR (255)   NULL,
    [Alias]                  NVARCHAR (255)   NULL,
    [Description]            NVARCHAR (MAX)   NULL,
    [Type]                   NVARCHAR (50)    NULL,
    [Telecom]                NVARCHAR (20)    NULL,
    [AddressID]              UNIQUEIDENTIFIER NULL,
    [PhysicalType]           NVARCHAR (50)    NULL,
    [Longitude]              DECIMAL (9, 6)   NULL,
    [Latitude]               DECIMAL (9, 6)   NULL,
    [Altitude]               DECIMAL (9, 6)   NULL,
    [ManagingOrganizationID] UNIQUEIDENTIFIER NULL,
    [PartOfID]               UNIQUEIDENTIFIER NULL,
    [EntityId]               UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Location__3214EC073C4874F8] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Medication]...';


GO
CREATE TABLE [dbo].[Medication] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [Code]             UNIQUEIDENTIFIER NOT NULL,
    [Status]           UNIQUEIDENTIFIER NULL,
    [IsBrand]          BIT              NULL,
    [Form]             UNIQUEIDENTIFIER NULL,
    [Quantity]         DECIMAL (18, 2)  NULL,
    [BatchNumber]      NVARCHAR (MAX)   NULL,
    [ExpirationDate]   DATETIME         NULL,
    [IsOverTheCounter] BIT              NULL,
    [Manufacturer]     UNIQUEIDENTIFIER NULL,
    [Ingredient]       UNIQUEIDENTIFIER NULL,
    [IngredientAmount] DECIMAL (18)     NULL,
    CONSTRAINT [PK__Medicati__3214EC076C92B62D] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[MedicationDispenseRequest]...';


GO
CREATE TABLE [dbo].[MedicationDispenseRequest] (
    [Id]                          UNIQUEIDENTIFIER NOT NULL,
    [ValidityPeriodStart]         DATETIME         NULL,
    [ValidityPeriodEnd]           DATETIME         NULL,
    [Quantity]                    DECIMAL (18, 2)  NULL,
    [ExpectedSupplyDurationValue] DECIMAL (18, 2)  NULL,
    [ExpectedSupplyDurationUnit]  DECIMAL (18, 2)  NULL,
    [ExpectedSupplyDurationCode]  DECIMAL (18, 2)  NULL,
    [PerformerGuid]               UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[MedicationRequest]...';


GO
CREATE TABLE [dbo].[MedicationRequest] (
    [Id]                                  UNIQUEIDENTIFIER NOT NULL,
    [NumberOfRepeatPrescriptionsAllowed]  INT              NULL,
    [NumberOfRepeatPrescriptionsIssued]   INT              NULL,
    [PrescriptionType]                    UNIQUEIDENTIFIER NULL,
    [CrossCareIdentifier]                 UNIQUEIDENTIFIER NULL,
    [GroupIdentifier]                     UNIQUEIDENTIFIER NULL,
    [Status]                              UNIQUEIDENTIFIER NULL,
    [Intent]                              UNIQUEIDENTIFIER NULL,
    [MedicationId]                        UNIQUEIDENTIFIER NULL,
    [Subject]                             UNIQUEIDENTIFIER NULL,
    [AuthoredOnUTC]                       DATETIME         NULL,
    [RecorderGuid]                        UNIQUEIDENTIFIER NULL,
    [DosageInstructionPatientInstruction] NVARCHAR (MAX)   NULL,
    [MedicationDispenseRequestId]         UNIQUEIDENTIFIER NULL,
    [AuthorizationExpiry]                 DATETIME         NULL,
    [Identifier]                          UNIQUEIDENTIFIER NULL,
    [Definition]                          UNIQUEIDENTIFIER NULL,
    [BasedOn]                             UNIQUEIDENTIFIER NULL,
    [Category]                            UNIQUEIDENTIFIER NULL,
    [Priority]                            UNIQUEIDENTIFIER NULL,
    [Context]                             UNIQUEIDENTIFIER NULL,
    [SupportingInformation]               UNIQUEIDENTIFIER NULL,
    [RequesterAgent]                      UNIQUEIDENTIFIER NULL,
    [RequesterOnBehalfOf]                 UNIQUEIDENTIFIER NULL,
    [Recorder]                            UNIQUEIDENTIFIER NULL,
    [Reason]                              UNIQUEIDENTIFIER NULL,
    [NoteAuthor]                          UNIQUEIDENTIFIER NULL,
    [Note]                                NVARCHAR (MAX)   NULL,
    [Dosage]                              UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Medicati__3214EC07905EAC71] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[MedicationStatement]...';


GO
CREATE TABLE [dbo].[MedicationStatement] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [Status]                   NVARCHAR (MAX)   NULL,
    [PrescribingAgencyCode]    NVARCHAR (MAX)   NULL,
    [PrescribingAgencyDisplay] NVARCHAR (MAX)   NULL,
    [LastIssueDateUTC]         DATETIME         NULL,
    [DateAssertedUTC]          DATETIME         NULL,
    [DosageLastChanged]        DATETIME         NULL,
    [MedicationId]             UNIQUEIDENTIFIER NULL,
    [EffectivePeriodStart]     DATETIME         NULL,
    [EffectivePeriodEnd]       DATETIME         NULL,
    [Subject]                  UNIQUEIDENTIFIER NULL,
    [Taken]                    NVARCHAR (MAX)   NULL,
    [Identifier]               UNIQUEIDENTIFIER NULL,
    [Dosage]                   UNIQUEIDENTIFIER NULL,
    [BasedOn]                  UNIQUEIDENTIFIER NULL,
    [PartOf]                   UNIQUEIDENTIFIER NULL,
    [Context]                  UNIQUEIDENTIFIER NULL,
    [Category]                 NVARCHAR (MAX)   NULL,
    [InformationSource]        UNIQUEIDENTIFIER NULL,
    [ReasonReference]          UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Observation]...';


GO
CREATE TABLE [dbo].[Observation] (
    [Id]                      UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]              NVARCHAR (200)   NULL,
    [Status]                  NVARCHAR (MAX)   NULL,
    [Category]                NVARCHAR (MAX)   NULL,
    [Code]                    UNIQUEIDENTIFIER NULL,
    [BasedOn]                 UNIQUEIDENTIFIER NULL,
    [SubjectId]               UNIQUEIDENTIFIER NULL,
    [ContextId]               UNIQUEIDENTIFIER NULL,
    [EffectiveDate]           DATETIME         NULL,
    [EffectiveDateFrom]       DATETIME         NULL,
    [EffectiveDateTo]         DATETIME         NULL,
    [Issued]                  DATETIME         NULL,
    [PerformerId]             UNIQUEIDENTIFIER NULL,
    [Interpretation]          NVARCHAR (MAX)   NULL,
    [DataAbsentReason]        NVARCHAR (MAX)   NULL,
    [Comment]                 NVARCHAR (MAX)   NULL,
    [BodySite]                NVARCHAR (MAX)   NULL,
    [Method]                  NVARCHAR (MAX)   NULL,
    [Device]                  UNIQUEIDENTIFIER NULL,
    [ReferenceText]           NVARCHAR (200)   NULL,
    [ReferenceRangeLow]       DECIMAL (18, 2)  NULL,
    [ReferenceRangeLowUnit]   NVARCHAR (200)   NULL,
    [ReferenceRangeHigh]      DECIMAL (18, 2)  NULL,
    [ReferenceRangeHighUnit]  NVARCHAR (200)   NULL,
    [ReferenceRangeType]      NVARCHAR (MAX)   NULL,
    [ReferenceRangeAppliesTo] NVARCHAR (MAX)   NULL,
    [ReferenceRangeAgeHigh]   DECIMAL (18, 2)  NULL,
    [ReferenceRangeAgeLow]    DECIMAL (18, 2)  NULL,
    [RelatedTo]               UNIQUEIDENTIFIER NULL,
    [Entityid]                UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Organization]...';


GO
CREATE TABLE [dbo].[Organization] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]     NVARCHAR (255)   NOT NULL,
    [ODSCode]        NVARCHAR (20)    NULL,
    [PeriodStart]    DATETIME         NULL,
    [PeriodEnd]      DATETIME         NULL,
    [Type]           NVARCHAR (50)    NOT NULL,
    [Name]           NVARCHAR (255)   NOT NULL,
    [Telecom]        NVARCHAR (20)    NULL,
    [MainLocationID] UNIQUEIDENTIFIER NULL,
    [AddressID]      UNIQUEIDENTIFIER NULL,
    [PartOfID]       UNIQUEIDENTIFIER NULL,
    [ContactID]      UNIQUEIDENTIFIER NULL,
    [EntityId]       UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK__Organiza__3214EC07861ED8BE] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Participant]...';


GO
CREATE TABLE [dbo].[Participant] (
    [Id]       UNIQUEIDENTIFIER NOT NULL,
    [Type]     NVARCHAR (MAX)   NULL,
    [Actor]    UNIQUEIDENTIFIER NULL,
    [Required] NVARCHAR (MAX)   NULL,
    [Status]   NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_Participant] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Patient]...';


GO
CREATE TABLE [dbo].[Patient] (
    [Id]                       UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]               NVARCHAR (255)   NOT NULL,
    [ManagingOrganization]     UNIQUEIDENTIFIER NOT NULL,
    [Practicioner]             UNIQUEIDENTIFIER NOT NULL,
    [HomeAddress]              UNIQUEIDENTIFIER NULL,
    [Gender]                   NVARCHAR (255)   NULL,
    [DateOfBirthUTC]           DATETIME         NOT NULL,
    [DateOfDeathUTC]           DATETIME         NULL,
    [Title]                    NVARCHAR (255)   NULL,
    [GivenName]                NVARCHAR (255)   NOT NULL,
    [MiddleNames]              NVARCHAR (MAX)   NULL,
    [Surname]                  NVARCHAR (255)   NOT NULL,
    [DateOfRegistrationUTC]    DATETIME         NULL,
    [NhsNumber]                NVARCHAR (255)   NULL,
    [PatientNumber]            NVARCHAR (255)   NULL,
    [PatientTypeDescription]   NVARCHAR (255)   NULL,
    [DummyType]                NVARCHAR (255)   NULL,
    [ResidentialInstituteCode] NVARCHAR (255)   NULL,
    [NHSNumberStatus]          NVARCHAR (255)   NULL,
    [CarerName]                NVARCHAR (255)   NULL,
    [CarerRelation]            NVARCHAR (255)   NULL,
    [PersonGuid]               NVARCHAR (255)   NULL,
    [DateOfDeactivation]       DATETIME         NULL,
    [Deleted]                  BIT              NULL,
    [Active]                   BIT              NULL,
    [SpineSensitive]           BIT              NULL,
    [IsConfidential]           BIT              NULL,
    [EmailAddress]             NVARCHAR (255)   NULL,
    [HomePhone]                NVARCHAR (20)    NULL,
    [MobilePhone]              NVARCHAR (20)    NULL,
    [ProcessingId]             NVARCHAR (255)   NULL,
    [Ethnicity]                NVARCHAR (255)   NULL,
    [Religion]                 NVARCHAR (255)   NULL,
    [NominatedPharmacy]        UNIQUEIDENTIFIER NULL,
    [EntityId]                 UNIQUEIDENTIFIER NULL,
    CONSTRAINT [PK__Patient__DBA60F19AE6332BC] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Patient_Address]...';


GO
CREATE TABLE [dbo].[Patient_Address] (
    [PatientId] UNIQUEIDENTIFIER NOT NULL,
    [AddressId] UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT [PK_Patient_Address] PRIMARY KEY CLUSTERED ([PatientId] ASC, [AddressId] ASC)
);


GO
PRINT N'Creating Table [dbo].[Patient_Contacts]...';


GO
CREATE TABLE [dbo].[Patient_Contacts] (
    [PatientId] UNIQUEIDENTIFIER NOT NULL,
    [ContactId] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Patient_Links]...';


GO
CREATE TABLE [dbo].[Patient_Links] (
    [PatientId]     UNIQUEIDENTIFIER NOT NULL,
    [LinkedPatient] UNIQUEIDENTIFIER NULL,
    [LinkedContact] UNIQUEIDENTIFIER NULL
);


GO
PRINT N'Creating Table [dbo].[Practicioner]...';


GO
CREATE TABLE [dbo].[Practicioner] (
    [Id]               UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]       NVARCHAR (255)   NOT NULL,
    [SdsUserId]        NVARCHAR (50)    NULL,
    [SdsRoleProfileId] NVARCHAR (50)    NULL,
    [Title]            NVARCHAR (20)    NULL,
    [GivenName]        NVARCHAR (100)   NULL,
    [MiddleNames]      NVARCHAR (250)   NULL,
    [Surname]          NVARCHAR (100)   NOT NULL,
    [Gender]           NVARCHAR (10)    NULL,
    [DateOfBirthUtc]   DATETIME         NULL,
    [AddressID]        UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Practicioner_Address]...';


GO
CREATE TABLE [dbo].[Practicioner_Address] (
    [PracticionerId] UNIQUEIDENTIFIER NOT NULL,
    [AddressId]      UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[PracticionerRole]...';


GO
CREATE TABLE [dbo].[PracticionerRole] (
    [Id]             UNIQUEIDENTIFIER NOT NULL,
    [OriginalId]     NVARCHAR (255)   NOT NULL,
    [Active]         BIT              NULL,
    [PeriodStart]    DATETIME         NULL,
    [PeriodEnd]      DATETIME         NULL,
    [Practicioner]   UNIQUEIDENTIFIER NOT NULL,
    [Organization]   UNIQUEIDENTIFIER NULL,
    [SDSJobRoleName] NVARCHAR (100)   NULL,
    [Speciality]     NVARCHAR (100)   NULL,
    [Location]       UNIQUEIDENTIFIER NULL,
    [Telecom]        NVARCHAR (50)    NULL,
    CONSTRAINT [PK_PracticionerRole] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ProcedureRequest]...';


GO
CREATE TABLE [dbo].[ProcedureRequest] (
    [Id]                         UNIQUEIDENTIFIER NOT NULL,
    [Identifier]                 UNIQUEIDENTIFIER NULL,
    [Status]                     NVARCHAR (255)   NULL,
    [Assigner]                   UNIQUEIDENTIFIER NULL,
    [RequisitionAssigner]        UNIQUEIDENTIFIER NULL,
    [Category]                   NVARCHAR (255)   NULL,
    [Code]                       NVARCHAR (255)   NULL,
    [Subject]                    UNIQUEIDENTIFIER NULL,
    [Conext]                     UNIQUEIDENTIFIER NULL,
    [Encounter]                  UNIQUEIDENTIFIER NULL,
    [RequestingOrganization]     UNIQUEIDENTIFIER NULL,
    [RequestingPracticioner]     UNIQUEIDENTIFIER NULL,
    [OnBehalfOf]                 UNIQUEIDENTIFIER NULL,
    [PerformerOrganization]      UNIQUEIDENTIFIER NULL,
    [PerformerPracticioner]      UNIQUEIDENTIFIER NULL,
    [Reason]                     NVARCHAR (255)   NULL,
    [ReasonReferenceCondition]   UNIQUEIDENTIFIER NULL,
    [ReasonReferenceObservation] UNIQUEIDENTIFIER NULL,
    [SupportingInfo]             UNIQUEIDENTIFIER NULL,
    [Specimen]                   UNIQUEIDENTIFIER NULL,
    [BodySite]                   NVARCHAR (255)   NULL,
    [NoteText]                   NVARCHAR (MAX)   NULL,
    [NoteAuthored]               DATETIME         NULL,
    [NoteAuthorPatient]          UNIQUEIDENTIFIER NULL,
    [NoteAuthorPracticioner]     UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Qualification]...';


GO
CREATE TABLE [dbo].[Qualification] (
    [Id]         UNIQUEIDENTIFIER NOT NULL,
    [Use]        NVARCHAR (20)    NULL,
    [Type]       NVARCHAR (50)    NULL,
    [System]     NVARCHAR (50)    NULL,
    [Value]      NVARCHAR (255)   NULL,
    [FromDate]   DATETIME         NULL,
    [ToDate]     DATETIME         NULL,
    [AssignerID] UNIQUEIDENTIFIER NULL,
    [IssuerID]   UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest]...';


GO
CREATE TABLE [dbo].[ReferralRequest] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Identifier]          UNIQUEIDENTIFIER NULL,
    [ActivityDefinition]  UNIQUEIDENTIFIER NULL,
    [Status]              NVARCHAR (MAX)   NULL,
    [Intent]              NVARCHAR (MAX)   NULL,
    [Type]                NVARCHAR (MAX)   NULL,
    [Priority]            NVARCHAR (MAX)   NULL,
    [ServiceRequested]    NVARCHAR (MAX)   NULL,
    [Subject]             UNIQUEIDENTIFIER NULL,
    [Context]             UNIQUEIDENTIFIER NULL,
    [OccurrenceDate]      DATETIME         NULL,
    [OccurrenceDateStart] DATETIME         NULL,
    [OccurrenceDateEnd]   DATETIME         NULL,
    [AuthoredOn]          DATETIME         NULL,
    [Requester]           UNIQUEIDENTIFIER NULL,
    [OnBehalfOf]          UNIQUEIDENTIFIER NULL,
    [Recipient]           UNIQUEIDENTIFIER NULL,
    [Description]         NVARCHAR (MAX)   NULL,
    [NoteAuthor]          UNIQUEIDENTIFIER NULL,
    [NoteText]            NVARCHAR (MAX)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest_BasedOn]...';


GO
CREATE TABLE [dbo].[ReferralRequest_BasedOn] (
    [EntityId]          UNIQUEIDENTIFIER NOT NULL,
    [ReferralRequestId] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest_ReasonReference]...';


GO
CREATE TABLE [dbo].[ReferralRequest_ReasonReference] (
    [Entity]          UNIQUEIDENTIFIER NOT NULL,
    [ReferralRequest] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest_RelevantHistory]...';


GO
CREATE TABLE [dbo].[ReferralRequest_RelevantHistory] (
    [Entity]          UNIQUEIDENTIFIER NOT NULL,
    [ReferralRequest] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest_Replaces]...';


GO
CREATE TABLE [dbo].[ReferralRequest_Replaces] (
    [ReplacingReferralRequestId] UNIQUEIDENTIFIER NOT NULL,
    [ReferralRequestId]          UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[ReferralRequest_SupportingInfo]...';


GO
CREATE TABLE [dbo].[ReferralRequest_SupportingInfo] (
    [Entity]          UNIQUEIDENTIFIER NOT NULL,
    [ReferralRequest] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Schedule]...';


GO
CREATE TABLE [dbo].[Schedule] (
    [Id]                   UNIQUEIDENTIFIER NOT NULL,
    [PracticionerRole]     NVARCHAR (50)    NULL,
    [ServiceCategory]      NVARCHAR (50)    NULL,
    [Speciality]           NVARCHAR (50)    NULL,
    [PlanningHorizonStart] DATETIME         NULL,
    [PlanningHorizonEnd]   DATETIME         NULL,
    [Comment]              NVARCHAR (MAX)   NULL,
    CONSTRAINT [PK_Schedule] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Schedule_Particpant]...';


GO
CREATE TABLE [dbo].[Schedule_Particpant] (
    [ScheduleId]    UNIQUEIDENTIFIER NOT NULL,
    [ParticipantId] UNIQUEIDENTIFIER NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Slot]...';


GO
CREATE TABLE [dbo].[Slot] (
    [Id]              UNIQUEIDENTIFIER NOT NULL,
    [DeliveryChannel] NVARCHAR (100)   NULL,
    [IdentifierId]    UNIQUEIDENTIFIER NULL,
    [ServiceType]     NVARCHAR (100)   NULL,
    [Speciality]      NVARCHAR (100)   NULL,
    [ScheduleId]      UNIQUEIDENTIFIER NULL,
    [Status]          NVARCHAR (100)   NULL,
    [Start]           DATETIME         NULL,
    [End]             DATETIME         NULL,
    [Overbooked]      BIT              NULL,
    [Comment]         NVARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Specimen]...';


GO
CREATE TABLE [dbo].[Specimen] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [IdentifierId]          UNIQUEIDENTIFIER NULL,
    [AccessionIdentifierId] UNIQUEIDENTIFIER NULL,
    [Status]                NVARCHAR (20)    NULL,
    [Type]                  NVARCHAR (20)    NULL,
    [SubjectId]             UNIQUEIDENTIFIER NULL,
    [ReceivedTime]          DATETIME         NULL,
    [ParentId]              UNIQUEIDENTIFIER NULL,
    [Request]               UNIQUEIDENTIFIER NULL,
    [FastingValueCode]      NVARCHAR (20)    NULL,
    [FastingDurationValue]  DECIMAL (18, 2)  NULL,
    [CollectorId]           UNIQUEIDENTIFIER NULL,
    [Collected]             DATETIME         NULL,
    [CollectedQuantity]     INT              NULL,
    [CollectionMethod]      NVARCHAR (20)    NULL,
    [CollectionBodySite]    NVARCHAR (20)    NULL,
    [ContainerIdentifierId] UNIQUEIDENTIFIER NULL,
    [SpecimenQuantity]      INT              NULL,
    [ContainerCapacity]     INT              NULL,
    [NoteText]              NVARCHAR (MAX)   NULL,
    [NoteAuthored]          DATETIME         NULL,
    [NoteAuthorId]          UNIQUEIDENTIFIER NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[StructureMap]...';


GO
CREATE TABLE [dbo].[StructureMap] (
    [Id]                  UNIQUEIDENTIFIER NOT NULL,
    [Identifier]          UNIQUEIDENTIFIER NULL,
    [Version]             VARCHAR (255)    NULL,
    [Name]                VARCHAR (255)    NULL,
    [Title]               VARCHAR (255)    NULL,
    [Status]              VARCHAR (255)    NULL,
    [Experimental]        BIT              NULL,
    [Date]                DATETIME         NULL,
    [Publisher]           VARCHAR (255)    NOT NULL,
    [ContactName]         VARCHAR (255)    NULL,
    [ContactNumber]       VARCHAR (255)    NULL,
    [Description]         VARCHAR (255)    NULL,
    [UseContextCode]      VARCHAR (255)    NULL,
    [UseContextQuantity]  DECIMAL (9, 2)   NULL,
    [UseContextRangeHigh] INT              NULL,
    [UseContextRangeLow]  INT              NULL,
    [Jurisdiction]        VARCHAR (255)    NULL,
    [Purpose]             VARCHAR (255)    NULL,
    [Copyright]           VARCHAR (255)    NULL,
    [Structure]           VARCHAR (255)    NULL,
    [Import]              VARCHAR (255)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Timing]...';


GO
CREATE TABLE [dbo].[Timing] (
    [Id]                 UNIQUEIDENTIFIER NOT NULL,
    [Event]              DATETIME2 (7)    NULL,
    [BoundsDuration]     DECIMAL (18, 9)  NULL,
    [BoundsDurationMax]  DECIMAL (18, 9)  NULL,
    [BoundsDurationUnit] NVARCHAR (50)    NULL,
    [Count]              INT              NULL,
    [CountMax]           INT              NULL,
    [Duration]           DECIMAL (18, 9)  NULL,
    [DurationMax]        DECIMAL (18, 9)  NULL,
    [DurationUnit]       NVARCHAR (50)    NULL,
    [Frequency]          INT              NULL,
    [FrequencyMax]       INT              NULL,
    [Period]             DECIMAL (18, 9)  NULL,
    [PeriodMax]          DECIMAL (18, 9)  NULL,
    [PeriodUnit]         NVARCHAR (50)    NULL,
    [DayOfWeek]          NVARCHAR (50)    NULL,
    [TimeOfDay]          INT              NULL,
    [When]               NVARCHAR (50)    NULL,
    [Offset]             INT              NULL,
    [Code]               NVARCHAR (50)    NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Foreign Key [dbo].[FK__ActivityD__Locat__0C85DE4D]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD CONSTRAINT [FK__ActivityD__Locat__0C85DE4D] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__ActivityD__Produ__72C60C4A]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD CONSTRAINT [FK__ActivityD__Produ__72C60C4A] FOREIGN KEY ([ProductId]) REFERENCES [dbo].[Medication] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ActivityDefinition]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD FOREIGN KEY ([TransformId]) REFERENCES [dbo].[StructureMap] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ActivityDefinition]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD FOREIGN KEY ([DosageId]) REFERENCES [dbo].[Dosage] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ActivityDefinition]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[ActivityDefinition]...';


GO
ALTER TABLE [dbo].[ActivityDefinition]
    ADD FOREIGN KEY ([RelatedArtifactId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__AllergyIn__Recor__2FCF1A8A]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK__AllergyIn__Recor__2FCF1A8A] FOREIGN KEY ([Recorder]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__AllergyIn__NoteA__31B762FC]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK__AllergyIn__NoteA__31B762FC] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AllergyIntollerance_Entity]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity] FOREIGN KEY ([Recorder]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AllergyIntollerance_Entity2]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity2] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AllergyIntollerance_Encounter]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK_AllergyIntollerance_Encounter] FOREIGN KEY ([Encounter]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__AllergyIn__Subje__2CF2ADDF]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK__AllergyIn__Subje__2CF2ADDF] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__AllergyIn__Asser__2DE6D218]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK__AllergyIn__Asser__2DE6D218] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AllergyIntollerance_DiagnosticReport]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK_AllergyIntollerance_DiagnosticReport] FOREIGN KEY ([Evidence]) REFERENCES [dbo].[DiagnosticReport] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__AllergyIn__Ident__2BFE89A6]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK__AllergyIn__Ident__2BFE89A6] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_AllergyIntollerance_Entity1]...';


GO
ALTER TABLE [dbo].[AllergyIntollerance]
    ADD CONSTRAINT [FK_AllergyIntollerance_Entity1] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Appointme__Booki__17036CC0]...';


GO
ALTER TABLE [dbo].[Appointment]
    ADD CONSTRAINT [FK__Appointme__Booki__17036CC0] FOREIGN KEY ([BookingOrganizationId]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Appointment]...';


GO
ALTER TABLE [dbo].[Appointment]
    ADD FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointment_Participant_Appointment]...';


GO
ALTER TABLE [dbo].[Appointment_Participant]
    ADD CONSTRAINT [FK_Appointment_Participant_Appointment] FOREIGN KEY ([AppointmentId]) REFERENCES [dbo].[Appointment] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointment_Participant_Participant]...';


GO
ALTER TABLE [dbo].[Appointment_Participant]
    ADD CONSTRAINT [FK_Appointment_Participant_Participant] FOREIGN KEY ([ParticipantId]) REFERENCES [dbo].[Participant] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointment_Slots_Appointment]...';


GO
ALTER TABLE [dbo].[Appointment_Slots]
    ADD CONSTRAINT [FK_Appointment_Slots_Appointment] FOREIGN KEY ([AppointmentId]) REFERENCES [dbo].[Appointment] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointment_Slots_Slot]...';


GO
ALTER TABLE [dbo].[Appointment_Slots]
    ADD CONSTRAINT [FK_Appointment_Slots_Slot] FOREIGN KEY ([SlotId]) REFERENCES [dbo].[Slot] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Compositio_Encounter]...';


GO
ALTER TABLE [dbo].[Composition]
    ADD CONSTRAINT [FK_Compositio_Encounter] FOREIGN KEY ([Encounter]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Compositio_Patient]...';


GO
ALTER TABLE [dbo].[Composition]
    ADD CONSTRAINT [FK_Compositio_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Compositio_Identifier]...';


GO
ALTER TABLE [dbo].[Composition]
    ADD CONSTRAINT [FK_Compositio_Identifier] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Compositio_Practicioner]...';


GO
ALTER TABLE [dbo].[Composition]
    ADD CONSTRAINT [FK_Compositio_Practicioner] FOREIGN KEY ([Author]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__NoteA__43D61337]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__NoteA__43D61337] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Actua__3E1D39E1]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__Actua__3E1D39E1] FOREIGN KEY ([ActualProblem]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__Subje__40F9A68C] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Conte__41EDCAC5]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__Conte__41EDCAC5] FOREIGN KEY ([Context]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Asser__42E1EEFE]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__Asser__42E1EEFE] FOREIGN KEY ([Asserter]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Condition__Ident__3D2915A8]...';


GO
ALTER TABLE [dbo].[Condition]
    ADD CONSTRAINT [FK__Condition__Ident__3D2915A8] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_Evidence_Condition]...';


GO
ALTER TABLE [dbo].[Condition_Evidence]
    ADD CONSTRAINT [FK_Condition_Evidence_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_Evidence_Entity]...';


GO
ALTER TABLE [dbo].[Condition_Evidence]
    ADD CONSTRAINT [FK_Condition_Evidence_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions]
    ADD CONSTRAINT [FK_Condition_RelatedClinicalConditions_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedClinicalConditions_Entity]...';


GO
ALTER TABLE [dbo].[Condition_RelatedClinicalConditions]
    ADD CONSTRAINT [FK_Condition_RelatedClinicalConditions_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedProblems_Condition]...';


GO
ALTER TABLE [dbo].[Condition_RelatedProblems]
    ADD CONSTRAINT [FK_Condition_RelatedProblems_Condition] FOREIGN KEY ([ConditionId]) REFERENCES [dbo].[Condition] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Condition_RelatedProblems_Entity]...';


GO
ALTER TABLE [dbo].[Condition_RelatedProblems]
    ADD CONSTRAINT [FK_Condition_RelatedProblems_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Contact_Organization]...';


GO
ALTER TABLE [dbo].[Contact]
    ADD CONSTRAINT [FK_Contact_Organization] FOREIGN KEY ([OrganizationId]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Contact]...';


GO
ALTER TABLE [dbo].[Contact]
    ADD FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Device_PartOf]...';


GO
ALTER TABLE [dbo].[Device]
    ADD CONSTRAINT [FK_Device_PartOf] FOREIGN KEY ([PartOf]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Device_Address]...';


GO
ALTER TABLE [dbo].[Device]
    ADD CONSTRAINT [FK_Device_Address] FOREIGN KEY ([Address]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Device_Contact]...';


GO
ALTER TABLE [dbo].[Device]
    ADD CONSTRAINT [FK_Device_Contact] FOREIGN KEY ([Contact]) REFERENCES [dbo].[Contact] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Device_Owner]...';


GO
ALTER TABLE [dbo].[Device]
    ADD CONSTRAINT [FK_Device_Owner] FOREIGN KEY ([Owner]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Device_Identifier]...';


GO
ALTER TABLE [dbo].[Device]
    ADD CONSTRAINT [FK_Device_Identifier] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_DiagnosticReport_ProcedureRequest]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD CONSTRAINT [FK_DiagnosticReport_ProcedureRequest] FOREIGN KEY ([ProcedureRequest]) REFERENCES [dbo].[ProcedureRequest] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[DiagnosticReport]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD FOREIGN KEY ([Specimen]) REFERENCES [dbo].[Specimen] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Diagnosti__Perfo__681373AD]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD CONSTRAINT [FK__Diagnosti__Perfo__681373AD] FOREIGN KEY ([Performer]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[DiagnosticReport]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[DiagnosticReport]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD FOREIGN KEY ([Result]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Diagnosti__Subje__1EA48E88]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD CONSTRAINT [FK__Diagnosti__Subje__1EA48E88] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[DiagnosticReport]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD FOREIGN KEY ([Encounter]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Diagnosti__Assig__37703C52]...';


GO
ALTER TABLE [dbo].[DiagnosticReport]
    ADD CONSTRAINT [FK__Diagnosti__Assig__37703C52] FOREIGN KEY ([Assigner]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Dosage_Timing]...';


GO
ALTER TABLE [dbo].[Dosage]
    ADD CONSTRAINT [FK_Dosage_Timing] FOREIGN KEY ([Timing]) REFERENCES [dbo].[Timing] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Encounter__Recor__4316F928]...';


GO
ALTER TABLE [dbo].[Encounter]
    ADD CONSTRAINT [FK__Encounter__Recor__4316F928] FOREIGN KEY ([RecorderId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Encounter_Encounter1]...';


GO
ALTER TABLE [dbo].[Encounter]
    ADD CONSTRAINT [FK_Encounter_Encounter1] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Encounter_Encounter]...';


GO
ALTER TABLE [dbo].[Encounter]
    ADD CONSTRAINT [FK_Encounter_Encounter] FOREIGN KEY ([Id]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Encounter__Perfo__4222D4EF]...';


GO
ALTER TABLE [dbo].[Encounter]
    ADD CONSTRAINT [FK__Encounter__Perfo__4222D4EF] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Encounter__Patie__412EB0B6]...';


GO
ALTER TABLE [dbo].[Encounter]
    ADD CONSTRAINT [FK__Encounter__Patie__412EB0B6] FOREIGN KEY ([PatientGuid]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Entity_EntityType]...';


GO
ALTER TABLE [dbo].[Entity]
    ADD CONSTRAINT [FK_Entity_EntityType] FOREIGN KEY ([EntityType]) REFERENCES [dbo].[EntityType] ([EntityType]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Equipment__PartO__46E78A0C]...';


GO
ALTER TABLE [dbo].[Equipment]
    ADD CONSTRAINT [FK__Equipment__PartO__46E78A0C] FOREIGN KEY ([PartOfID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Equipment__Addre__440B1D61]...';


GO
ALTER TABLE [dbo].[Equipment]
    ADD CONSTRAINT [FK__Equipment__Addre__440B1D61] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Equipment_Entity]...';


GO
ALTER TABLE [dbo].[Equipment]
    ADD CONSTRAINT [FK_Equipment_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Equipment__Owner__45F365D3]...';


GO
ALTER TABLE [dbo].[Equipment]
    ADD CONSTRAINT [FK__Equipment__Owner__45F365D3] FOREIGN KEY ([OwnerID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Equipment__Conta__44FF419A]...';


GO
ALTER TABLE [dbo].[Equipment]
    ADD CONSTRAINT [FK__Equipment__Conta__44FF419A] FOREIGN KEY ([ContactID]) REFERENCES [dbo].[Contact] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Immunization_Entity]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK_Immunization_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__NoteA__73BA3083]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__NoteA__73BA3083] FOREIGN KEY ([NoteAuthorId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__Autho__75A278F5]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__Autho__75A278F5] FOREIGN KEY ([AuthorityId]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__React__74AE54BC]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__React__74AE54BC] FOREIGN KEY ([ReactionDetailId]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__Locat__72C60C4A]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__Locat__72C60C4A] FOREIGN KEY ([LocationId]) REFERENCES [dbo].[Location] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__Subje__6FE99F9F]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__Subje__6FE99F9F] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__Encou__70DDC3D8]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__Encou__70DDC3D8] FOREIGN KEY ([EncounterId]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Immunizat__Actor__71D1E811]...';


GO
ALTER TABLE [dbo].[Immunization]
    ADD CONSTRAINT [FK__Immunizat__Actor__71D1E811] FOREIGN KEY ([ActorId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Location__PartOf__4D5F7D71]...';


GO
ALTER TABLE [dbo].[Location]
    ADD CONSTRAINT [FK__Location__PartOf__4D5F7D71] FOREIGN KEY ([PartOfID]) REFERENCES [dbo].[Location] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Location__Addres__4F47C5E3]...';


GO
ALTER TABLE [dbo].[Location]
    ADD CONSTRAINT [FK__Location__Addres__4F47C5E3] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Location__Managi__4E53A1AA]...';


GO
ALTER TABLE [dbo].[Location]
    ADD CONSTRAINT [FK__Location__Managi__4E53A1AA] FOREIGN KEY ([ManagingOrganizationID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Medication_Organization]...';


GO
ALTER TABLE [dbo].[Medication]
    ADD CONSTRAINT [FK_Medication_Organization] FOREIGN KEY ([Manufacturer]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[MedicationDispenseRequest]...';


GO
ALTER TABLE [dbo].[MedicationDispenseRequest]
    ADD FOREIGN KEY ([PerformerGuid]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Patie__3A4CA8FD]...';


GO
ALTER TABLE [dbo].[MedicationRequest]
    ADD CONSTRAINT [FK__Medicatio__Patie__3A4CA8FD] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Medic__3864608B]...';


GO
ALTER TABLE [dbo].[MedicationRequest]
    ADD CONSTRAINT [FK__Medicatio__Medic__3864608B] FOREIGN KEY ([MedicationId]) REFERENCES [dbo].[Medication] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Recor__3B40CD36]...';


GO
ALTER TABLE [dbo].[MedicationRequest]
    ADD CONSTRAINT [FK__Medicatio__Recor__3B40CD36] FOREIGN KEY ([RecorderGuid]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Medic__395884C4]...';


GO
ALTER TABLE [dbo].[MedicationRequest]
    ADD CONSTRAINT [FK__Medicatio__Medic__395884C4] FOREIGN KEY ([MedicationDispenseRequestId]) REFERENCES [dbo].[MedicationDispenseRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Medic__3D2915A8]...';


GO
ALTER TABLE [dbo].[MedicationStatement]
    ADD CONSTRAINT [FK__Medicatio__Medic__3D2915A8] FOREIGN KEY ([MedicationId]) REFERENCES [dbo].[Medication] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Medicatio__Patie__3E1D39E1]...';


GO
ALTER TABLE [dbo].[MedicationStatement]
    ADD CONSTRAINT [FK__Medicatio__Patie__3E1D39E1] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Coding]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Coding] FOREIGN KEY ([Code]) REFERENCES [dbo].[Coding] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__basedOn]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__basedOn] FOREIGN KEY ([BasedOn]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Observation]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Device]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Device] FOREIGN KEY ([Device]) REFERENCES [dbo].[Device] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Conte__534D60F1]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Conte__534D60F1] FOREIGN KEY ([ContextId]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Perf]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Perf] FOREIGN KEY ([PerformerId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Subje__40F9A68C]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Subje__40F9A68C] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Entity]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Entity] FOREIGN KEY ([Entityid]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Observati__Observation]...';


GO
ALTER TABLE [dbo].[Observation]
    ADD CONSTRAINT [FK__Observati__Observation] FOREIGN KEY ([RelatedTo]) REFERENCES [dbo].[Observation] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Organizat__PartO__5BAD9CC8]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD CONSTRAINT [FK__Organizat__PartO__5BAD9CC8] FOREIGN KEY ([PartOfID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Organizat__Addre__5AB9788F]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD CONSTRAINT [FK__Organizat__Addre__5AB9788F] FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Organizat__Conta__5CA1C101]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD CONSTRAINT [FK__Organizat__Conta__5CA1C101] FOREIGN KEY ([ContactID]) REFERENCES [dbo].[Contact] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Organization_Location]...';


GO
ALTER TABLE [dbo].[Organization]
    ADD CONSTRAINT [FK_Organization_Location] FOREIGN KEY ([MainLocationID]) REFERENCES [dbo].[Location] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Participa__Actor__078C1F06]...';


GO
ALTER TABLE [dbo].[Participant]
    ADD CONSTRAINT [FK__Participa__Actor__078C1F06] FOREIGN KEY ([Actor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Patient]...';


GO
ALTER TABLE [dbo].[Patient]
    ADD CONSTRAINT [FK_Patient_Patient] FOREIGN KEY ([Id]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Organization1]...';


GO
ALTER TABLE [dbo].[Patient]
    ADD CONSTRAINT [FK_Patient_Organization1] FOREIGN KEY ([NominatedPharmacy]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Organization]...';


GO
ALTER TABLE [dbo].[Patient]
    ADD CONSTRAINT [FK_Patient_Organization] FOREIGN KEY ([ManagingOrganization]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Practicioner]...';


GO
ALTER TABLE [dbo].[Patient]
    ADD CONSTRAINT [FK_Patient_Practicioner] FOREIGN KEY ([Practicioner]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Address_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Address]
    ADD CONSTRAINT [FK_Patient_Address_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Address_Address]...';


GO
ALTER TABLE [dbo].[Patient_Address]
    ADD CONSTRAINT [FK_Patient_Address_Address] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Contacts_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Contacts]
    ADD CONSTRAINT [FK_Patient_Contacts_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Contacts_Contact]...';


GO
ALTER TABLE [dbo].[Patient_Contacts]
    ADD CONSTRAINT [FK_Patient_Contacts_Contact] FOREIGN KEY ([ContactId]) REFERENCES [dbo].[Contact] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Links_Patient1]...';


GO
ALTER TABLE [dbo].[Patient_Links]
    ADD CONSTRAINT [FK_Patient_Links_Patient1] FOREIGN KEY ([LinkedPatient]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Links_Patient]...';


GO
ALTER TABLE [dbo].[Patient_Links]
    ADD CONSTRAINT [FK_Patient_Links_Patient] FOREIGN KEY ([PatientId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Patient_Links_Contact]...';


GO
ALTER TABLE [dbo].[Patient_Links]
    ADD CONSTRAINT [FK_Patient_Links_Contact] FOREIGN KEY ([LinkedContact]) REFERENCES [dbo].[Contact] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Practicioner]...';


GO
ALTER TABLE [dbo].[Practicioner]
    ADD FOREIGN KEY ([AddressID]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Practicioner_Address_Address]...';


GO
ALTER TABLE [dbo].[Practicioner_Address]
    ADD CONSTRAINT [FK_Practicioner_Address_Address] FOREIGN KEY ([AddressId]) REFERENCES [dbo].[Address] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Practicioner_Address_Practicioner]...';


GO
ALTER TABLE [dbo].[Practicioner_Address]
    ADD CONSTRAINT [FK_Practicioner_Address_Practicioner] FOREIGN KEY ([PracticionerId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PracticionerRole_Practicioner]...';


GO
ALTER TABLE [dbo].[PracticionerRole]
    ADD CONSTRAINT [FK_PracticionerRole_Practicioner] FOREIGN KEY ([Practicioner]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PracticionerRole_Location]...';


GO
ALTER TABLE [dbo].[PracticionerRole]
    ADD CONSTRAINT [FK_PracticionerRole_Location] FOREIGN KEY ([Location]) REFERENCES [dbo].[Location] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_PracticionerRole_Organization]...';


GO
ALTER TABLE [dbo].[PracticionerRole]
    ADD CONSTRAINT [FK_PracticionerRole_Organization] FOREIGN KEY ([Organization]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_OnBehalfOf]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_OnBehalfOf] FOREIGN KEY ([OnBehalfOf]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_ConextE]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_ConextE] FOREIGN KEY ([Conext]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_Encounter]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_Encounter] FOREIGN KEY ([Encounter]) REFERENCES [dbo].[Encounter] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_RequestingOrganization]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_RequestingOrganization] FOREIGN KEY ([RequestingOrganization]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_Assigner]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_Assigner] FOREIGN KEY ([Assigner]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_RequestingPracticioner]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_RequestingPracticioner] FOREIGN KEY ([RequestingPracticioner]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_Subject]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_Subject] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_RequisitionAssigner]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_RequisitionAssigner] FOREIGN KEY ([RequisitionAssigner]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProcedureRequest_Identifier]...';


GO
ALTER TABLE [dbo].[ProcedureRequest]
    ADD CONSTRAINT [FK_ProcedureRequest_Identifier] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Qualifica__Assig__76619304]...';


GO
ALTER TABLE [dbo].[Qualification]
    ADD CONSTRAINT [FK__Qualifica__Assig__76619304] FOREIGN KEY ([AssignerID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Qualifica__Issue__756D6ECB]...';


GO
ALTER TABLE [dbo].[Qualification]
    ADD CONSTRAINT [FK__Qualifica__Issue__756D6ECB] FOREIGN KEY ([IssuerID]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Entity] FOREIGN KEY ([Context]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Entity1]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Entity1] FOREIGN KEY ([Requester]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Patient]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Patient] FOREIGN KEY ([Subject]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Entity2]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Entity2] FOREIGN KEY ([Recipient]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Organization]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Organization] FOREIGN KEY ([OnBehalfOf]) REFERENCES [dbo].[Organization] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Entity3]...';


GO
ALTER TABLE [dbo].[ReferralRequest]
    ADD CONSTRAINT [FK_ReferralRequest_Entity3] FOREIGN KEY ([NoteAuthor]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_BasedOn_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_BasedOn]
    ADD CONSTRAINT [FK_ReferralRequest_BasedOn_Entity] FOREIGN KEY ([EntityId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_BasedOn_ReferralRequest]...';


GO
ALTER TABLE [dbo].[ReferralRequest_BasedOn]
    ADD CONSTRAINT [FK_ReferralRequest_BasedOn_ReferralRequest] FOREIGN KEY ([ReferralRequestId]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_ReasonReference_ReferralRequest]...';


GO
ALTER TABLE [dbo].[ReferralRequest_ReasonReference]
    ADD CONSTRAINT [FK_ReferralRequest_ReasonReference_ReferralRequest] FOREIGN KEY ([ReferralRequest]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_ReasonReference_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_ReasonReference]
    ADD CONSTRAINT [FK_ReferralRequest_ReasonReference_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_RelevantHistory_ReferralRequest]...';


GO
ALTER TABLE [dbo].[ReferralRequest_RelevantHistory]
    ADD CONSTRAINT [FK_ReferralRequest_RelevantHistory_ReferralRequest] FOREIGN KEY ([ReferralRequest]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_RelevantHistory_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_RelevantHistory]
    ADD CONSTRAINT [FK_ReferralRequest_RelevantHistory_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Replaces_ReferralRequest]...';


GO
ALTER TABLE [dbo].[ReferralRequest_Replaces]
    ADD CONSTRAINT [FK_ReferralRequest_Replaces_ReferralRequest] FOREIGN KEY ([ReplacingReferralRequestId]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_Replaces_ReferralRequest1]...';


GO
ALTER TABLE [dbo].[ReferralRequest_Replaces]
    ADD CONSTRAINT [FK_ReferralRequest_Replaces_ReferralRequest1] FOREIGN KEY ([ReferralRequestId]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_SupportingInfo_ReferralRequest]...';


GO
ALTER TABLE [dbo].[ReferralRequest_SupportingInfo]
    ADD CONSTRAINT [FK_ReferralRequest_SupportingInfo_ReferralRequest] FOREIGN KEY ([ReferralRequest]) REFERENCES [dbo].[ReferralRequest] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ReferralRequest_SupportingInfo_Entity]...';


GO
ALTER TABLE [dbo].[ReferralRequest_SupportingInfo]
    ADD CONSTRAINT [FK_ReferralRequest_SupportingInfo_Entity] FOREIGN KEY ([Entity]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Schedule_Particpant_Participant]...';


GO
ALTER TABLE [dbo].[Schedule_Particpant]
    ADD CONSTRAINT [FK_Schedule_Particpant_Participant] FOREIGN KEY ([ParticipantId]) REFERENCES [dbo].[Participant] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Schedule_Particpant_Schedule]...';


GO
ALTER TABLE [dbo].[Schedule_Particpant]
    ADD CONSTRAINT [FK_Schedule_Particpant_Schedule] FOREIGN KEY ([ScheduleId]) REFERENCES [dbo].[Schedule] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Slot]...';


GO
ALTER TABLE [dbo].[Slot]
    ADD FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Slot]...';


GO
ALTER TABLE [dbo].[Slot]
    ADD FOREIGN KEY ([ScheduleId]) REFERENCES [dbo].[Schedule] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([NoteAuthorId]) REFERENCES [dbo].[Entity] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([IdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([CollectorId]) REFERENCES [dbo].[Practicioner] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([ContainerIdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Specimen_ProcedureRequest]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD CONSTRAINT [FK_Specimen_ProcedureRequest] FOREIGN KEY ([Request]) REFERENCES [dbo].[ProcedureRequest] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([AccessionIdentifierId]) REFERENCES [dbo].[Identifier] ([Id]);


GO
PRINT N'Creating Foreign Key unnamed constraint on [dbo].[Specimen]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD FOREIGN KEY ([ParentId]) REFERENCES [dbo].[Specimen] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK__Specimen__Subjec__6FB49575]...';


GO
ALTER TABLE [dbo].[Specimen]
    ADD CONSTRAINT [FK__Specimen__Subjec__6FB49575] FOREIGN KEY ([SubjectId]) REFERENCES [dbo].[Patient] ([Id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_StructureMap_Identifier]...';


GO
ALTER TABLE [dbo].[StructureMap]
    ADD CONSTRAINT [FK_StructureMap_Identifier] FOREIGN KEY ([Identifier]) REFERENCES [dbo].[Identifier] ([Id]);


GO
/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

BEGIN
	-- Disable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? NOCHECK CONSTRAINT all'
    DELETE FROM[dbo].[EntityType]
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (1,N'Organization')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (2,N'Location')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (3,N'Patient')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (4,N'Practitioner')
	INSERT [dbo].[EntityType] ([EntityType], [EntityName]) VALUES (5,N'Observation')
	
	-- Re-enable constraints for all tables:
	EXEC sp_msforeachtable 'ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all';	

END
GO

GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
